version: "3.8"

services:
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: always

  app:
    build: .
    container_name: node-app
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis-server
      REDIS_PORT: 6379
    ports:
      - "5000:5000"
    restart: always
